### ISSUE TITLE
popover too wide

### ISSUE THREAD

**Issue by fossfreedom** [AkiraMiyakoda/budgie-performance-gauge-applet#1]
![image](https://user-images.githubusercontent.com/996240/127051792-0fd8ef16-dabb-4dfd-a8fc-6cd0ab2a3742.png)

Can I ask why such a huge popover ?

**Comment by AkiraMiyakoda** [comment]
@fossfreedom
As you see, the huge popover results from long mount point names.
Now it is resolved as you have suggested in #2.
